
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ITLAB2-PC01-STUDENT
 */
    public class LoginForm extends javax.swing.JFrame {

   
        String userspath = "C:\\Users\\Kristine L. Lopez\\Documents\\Github\\House-Cleaning-Booking-System\\HouseCleaningBookingSystem\\fd\\house-cleaning\\House_Cleaning_Service\\Accounts.txt";
        
    // Method to check if the entered username and password match any user in the file
    public boolean checkCredentials(String username, String password) {
        try {
            try (BufferedReader reader = new BufferedReader(new FileReader(userspath))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] userData = line.split(",");
                    String storedUsername = userData[0];
                      String storedPassword = userData[1];
                    if (storedUsername.equals(username) && storedPassword.equals(password)) {
                        reader.close();
                        return true; 
                    }
                }
            }
        } catch (IOException e) {
        }
        return false; // No matching user found
    }
        
      public static void updatePassword(String username, String newPassword) {
       String userspath = "C:\\Users\\Kristine L. Lopez\\Documents\\Github\\House-Cleaning-Booking-System\\HouseCleaningBookingSystem\\fd\\house-cleaning\\House_Cleaning_Service\\Accounts.txt";
    
    // Create StringBuilder to store updated contents
    StringBuilder updatedContents = new StringBuilder();
    
    try (BufferedReader reader = new BufferedReader(new FileReader(userspath))) {
        String line;
        while ((line = reader.readLine()) != null) {
            // Split each line by comma to get username and password
            String[] parts = line.split(",");
            String existingUsername = parts[0].trim();
            String existingPassword = parts[1].trim();
            
            // Check if this is the user we want to update
            if (existingUsername.equals(username)) {
                // Update the password
                updatedContents.append(username).append(",").append(newPassword).append("\n");
            } else {
                // Keep the existing data for other users
                updatedContents.append(line).append("\n");
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
        // Handle file reading error
    }
    
    // Write the updated contents back to the file
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(userspath))) {
        writer.write(updatedContents.toString());
    } catch (IOException e) {
        e.printStackTrace();
        // Handle file writing error
    }
      }

     

       private void updateSelectedDateLabel() {
        String selectedMonth = (String) MONTH.getSelectedItem();
        String selectedDate = (String) DATE.getSelectedItem();
        String selectedYear = (String) YEAR.getSelectedItem();

        ca_birthdate.setText( selectedMonth + " " + selectedDate + ", " + selectedYear);
    }

         
         
      
    public void writeUserData(String username, String password) {
        try {
            try (FileWriter writer = new FileWriter(userspath, true)) {
                writer.write(username + "," + password + "\n");
            }
        } catch (IOException e) {
        }
    }
    
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        headerPanel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        SideSignUnButton = new javax.swing.JButton();
        SideCreateAccountButton = new javax.swing.JButton();
        SideLabel = new javax.swing.JLabel();
        centerWhiteDesignPAnel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        LoginForm = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        loginpanel = new javax.swing.JPanel();
        login_username = new javax.swing.JTextField();
        logintxt_password = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        login_password = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        logintxt_username1 = new javax.swing.JLabel();
        seePassword = new javax.swing.JCheckBox();
        CreateAccount = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ca_txtfullname = new javax.swing.JLabel();
        ca_txtusername = new javax.swing.JLabel();
        ca_txtpassword = new javax.swing.JLabel();
        ca_fullname = new javax.swing.JTextField();
        ca_username = new javax.swing.JTextField();
        ca_password = new javax.swing.JPasswordField();
        ca_createbutton = new javax.swing.JButton();
        ca_txtemail = new javax.swing.JLabel();
        ca_email = new javax.swing.JTextField();
        ca_txtemail1 = new javax.swing.JLabel();
        ca_phonenumber = new javax.swing.JTextField();
        ca_txtemail2 = new javax.swing.JLabel();
        ca_txtaddress = new javax.swing.JLabel();
        ca_txtgender = new javax.swing.JLabel();
        ca_age = new javax.swing.JTextField();
        ca_address = new javax.swing.JTextField();
        ca_txtemail4 = new javax.swing.JLabel();
        ca_birthdate = new javax.swing.JTextField();
        ca_gender = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        MONTH = new javax.swing.JComboBox<>();
        DATE = new javax.swing.JComboBox<>();
        YEAR = new javax.swing.JComboBox<>();

        jLabel6.setText("jLabel6");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(2, 56, 110));
        headerPanel.setForeground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("------------------------------------------------------------------------------------------------------------");
        headerPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 980, 20));

        jLabel34.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("-----------------------------------------------------------------------------------------------------------");
        headerPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 970, 20));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOUSE CLEANING BOOKING SYSYTEM");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), " WELCOME TO ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 980, 160));

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 200));

        sidePanel.setBackground(new java.awt.Color(0, 73, 141));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideSignUnButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        SideSignUnButton.setText("Sign - in");
        SideSignUnButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SideSignUnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SideSignUnButtonActionPerformed(evt);
            }
        });
        sidePanel.add(SideSignUnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 220, 40));

        SideCreateAccountButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        SideCreateAccountButton.setText("Create Account");
        SideCreateAccountButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SideCreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SideCreateAccountButtonActionPerformed(evt);
            }
        });
        sidePanel.add(SideCreateAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 220, 40));

        SideLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        sidePanel.add(SideLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 260, 280));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 280, 590));

        centerWhiteDesignPAnel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout centerWhiteDesignPAnelLayout = new javax.swing.GroupLayout(centerWhiteDesignPAnel);
        centerWhiteDesignPAnel.setLayout(centerWhiteDesignPAnelLayout);
        centerWhiteDesignPAnelLayout.setHorizontalGroup(
            centerWhiteDesignPAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        centerWhiteDesignPAnelLayout.setVerticalGroup(
            centerWhiteDesignPAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(centerWhiteDesignPAnel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1000, 10));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 102));

        LoginForm.setBackground(new java.awt.Color(0, 82, 162));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" * * * * * SIGN - IN * * * * *");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        loginpanel.setBackground(new java.awt.Color(204, 204, 255));
        loginpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        loginpanel.setOpaque(false);
        loginpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_username.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        login_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginpanel.add(login_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 340, 40));

        logintxt_password.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logintxt_password.setForeground(new java.awt.Color(255, 255, 255));
        logintxt_password.setText("PASSWORD:");
        loginpanel.add(logintxt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 130, 30));

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(51, 51, 51));
        LoginButton.setText("LOGIN");
        LoginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        loginpanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 240, 30));

        login_password.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        login_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginpanel.add(login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 340, 40));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("-----------------------------------------------------------");
        loginpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("-----------------------------------------------------------");
        loginpanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        logintxt_username1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logintxt_username1.setForeground(new java.awt.Color(255, 255, 255));
        logintxt_username1.setText("USERNAME:");
        loginpanel.add(logintxt_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, 30));

        seePassword.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        seePassword.setForeground(new java.awt.Color(255, 255, 255));
        seePassword.setText("See Password");
        seePassword.setOpaque(false);
        seePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePasswordActionPerformed(evt);
            }
        });
        loginpanel.add(seePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 150, -1));

        javax.swing.GroupLayout LoginFormLayout = new javax.swing.GroupLayout(LoginForm);
        LoginForm.setLayout(LoginFormLayout);
        LoginFormLayout.setHorizontalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginFormLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginFormLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        LoginFormLayout.setVerticalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginFormLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        jTabbedPane1.addTab("tab1", LoginForm);

        CreateAccount.setBackground(new java.awt.Color(0, 82, 162));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" * * * * * CREATE ACCOUNT * * * * *");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ca_txtfullname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtfullname.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtfullname.setText("FULLNAME:");
        jPanel3.add(ca_txtfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 56, -1, 20));

        ca_txtusername.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtusername.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtusername.setText("USERNAME:");
        jPanel3.add(ca_txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        ca_txtpassword.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtpassword.setText("PASSWORD:");
        jPanel3.add(ca_txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        ca_fullname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ca_fullname.setForeground(new java.awt.Color(51, 51, 51));
        ca_fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(ca_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 219, 30));

        ca_username.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ca_username.setForeground(new java.awt.Color(51, 51, 51));
        ca_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(ca_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 218, 30));

        ca_password.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ca_password.setForeground(new java.awt.Color(51, 51, 51));
        ca_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(ca_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 218, 30));

        ca_createbutton.setBackground(new java.awt.Color(255, 255, 255));
        ca_createbutton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_createbutton.setForeground(new java.awt.Color(51, 51, 51));
        ca_createbutton.setText("CREATE");
        ca_createbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ca_createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ca_createbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(ca_createbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 230, 30));

        ca_txtemail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtemail.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtemail.setText("EMAIL:");
        jPanel3.add(ca_txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 50, -1));

        ca_email.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ca_email.setForeground(new java.awt.Color(51, 51, 51));
        ca_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(ca_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 230, 30));

        ca_txtemail1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtemail1.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtemail1.setText("PHONE NO:");
        jPanel3.add(ca_txtemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 80, -1));

        ca_phonenumber.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ca_phonenumber.setForeground(new java.awt.Color(51, 51, 51));
        ca_phonenumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(ca_phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 230, 30));

        ca_txtemail2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtemail2.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtemail2.setText("AGE:");
        jPanel3.add(ca_txtemail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 40, -1));

        ca_txtaddress.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtaddress.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtaddress.setText("ADDRESS:");
        jPanel3.add(ca_txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        ca_txtgender.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtgender.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtgender.setText("GENDER:");
        jPanel3.add(ca_txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        ca_age.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ca_age.setForeground(new java.awt.Color(51, 51, 51));
        ca_age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(ca_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 230, 30));

        ca_address.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ca_address.setForeground(new java.awt.Color(51, 51, 51));
        ca_address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(ca_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 220, 30));

        ca_txtemail4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ca_txtemail4.setForeground(new java.awt.Color(255, 255, 255));
        ca_txtemail4.setText("BIRTHDATE: MM-dd-yyyy");
        jPanel3.add(ca_txtemail4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        ca_birthdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ca_birthdate.setForeground(new java.awt.Color(51, 51, 51));
        ca_birthdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(ca_birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 230, 30));

        ca_gender.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ca_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Prefer not to say" }));
        jPanel3.add(ca_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 210, 30));

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("-----------------------------------------------------------------");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 590, -1));

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("-----------------------------------------------------------------");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 590, -1));

        MONTH.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MONTH.setForeground(new java.awt.Color(51, 51, 51));
        MONTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Febuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        MONTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MONTHActionPerformed(evt);
            }
        });
        jPanel3.add(MONTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 90, 20));

        DATE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        DATE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        DATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATEActionPerformed(evt);
            }
        });
        jPanel3.add(DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 60, 20));

        YEAR.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        YEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2005", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        YEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YEARActionPerformed(evt);
            }
        });
        jPanel3.add(YEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 80, 20));

        javax.swing.GroupLayout CreateAccountLayout = new javax.swing.GroupLayout(CreateAccount);
        CreateAccount.setLayout(CreateAccountLayout);
        CreateAccountLayout.setHorizontalGroup(
            CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAccountLayout.createSequentialGroup()
                .addGroup(CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateAccountLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateAccountLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        CreateAccountLayout.setVerticalGroup(
            CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateAccountLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("tab2", CreateAccount);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 720, 640));

        setSize(new java.awt.Dimension(1016, 839));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed

       String username = login_username.getText().trim();
       String password = login_password.getText();

       String adminUsername = "xhinsade";
       String adminPassword = "xhinsade123";

       if (username.isEmpty() || password.isEmpty()) {
       JOptionPane.showMessageDialog(null, "Please fill out both username and password fields", "Error", JOptionPane.ERROR_MESSAGE);
       } else {
       if (checkCredentials(username, password)) {
        JOptionPane.showMessageDialog(null, "You have successfully logged in");
        UserDashboard menu = new UserDashboard();
        menu.setVisible(true);
        this.dispose();
         } else if (username.equals(adminUsername) && password.equals(adminPassword)) {
        JOptionPane.showMessageDialog(null, "You have successfully logged in");
        AdminDashboard admin = new AdminDashboard();
        admin.setVisible(true);
        this.dispose();
        } else {
        JOptionPane.showMessageDialog(null, "Incorrect username or password", "Error", JOptionPane.ERROR_MESSAGE);
       }
       }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void seePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePasswordActionPerformed
       
        if (seePassword.isSelected())
        {
            login_password.setEchoChar((char)0);
        }
        else 
        { 
            login_password.setEchoChar('*');
        }
    
    }//GEN-LAST:event_seePasswordActionPerformed

    private void ca_createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ca_createbuttonActionPerformed

        
        String userspath = "C:\\Users\\Kristine L. Lopez\\Documents\\Github\\House-Cleaning-Booking-System\\HouseCleaningBookingSystem\\fd\\house-cleaning\\House_Cleaning_Service\\Accounts.txt";
    
        File f = new File(userspath);

        String fullname = ca_fullname.getText().trim();
        String username = ca_username.getText().trim();
        String password = ca_password.getText();
        String address = ca_address.getText().trim();
        String email = ca_email.getText().trim();
        String age = ca_age.getText().trim();
        String number = ca_phonenumber.getText().trim();
        String birthdate = ca_birthdate.getText().trim();
        String gender = ca_gender.getSelectedItem().toString();

        
       

        if (!fullname.matches("[a-zA-Z- ]+")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid name (only alphabetic characters and spaces)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if ( !username.matches("[a-zA-Z0-9]+")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid username (only alphanumeric characters)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!address.matches("[a-zA-Z0-9 ]+")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid address (only alphabetic characters, spaces, and numbers)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!number.matches("\\d{11}")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid 11-digit phone number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
        if (age.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter your age", "Error", JOptionPane.ERROR_MESSAGE);
    return;
        }

       try {
          int Age = Integer.parseInt(age);
            if (Age <= 17) {
        JOptionPane.showMessageDialog(this, "Please enter a valid age (must be 18 or older)", "Error", JOptionPane.ERROR_MESSAGE);
        return;
       }
         } catch (NumberFormatException ex) {
           JOptionPane.showMessageDialog(this, "Please enter a valid age (numeric value)", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        
        }
        
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to create this account?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            writeUserData(username, password);

            String dataFilePath = "UserPersonalData.txt";
            try (FileWriter fileWriter = new FileWriter(dataFilePath, true)) {
                fileWriter.write("Full Name: " + fullname + "\n");
                fileWriter.write("Username: " + username + "\n");
                fileWriter.write("Address: " + address + "\n");
                fileWriter.write("Email: " + email + "\n");
                fileWriter.write("Age: " + age + "\n");
                fileWriter.write("Phone Number: " + number + "\n");
                fileWriter.write("Birthdate: " + birthdate + "\n");
                fileWriter.write("Gender: " + gender + "\n");
                fileWriter.write("------------------------\n");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "You've successfully created an account. Logging you in...");

                // Check if the user credentials are valid (just created)
                if (checkCredentials(username, password)) {
                    UserDashboard menu = new UserDashboard();
                    menu.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Login failed after account creation. Please log in manually.", "Error", JOptionPane.ERROR_MESSAGE);
                    jTabbedPane1.setSelectedIndex(0); // Back to login tab
                }
        }
        

    }//GEN-LAST:event_ca_createbuttonActionPerformed

    private void SideSignUnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SideSignUnButtonActionPerformed
        
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_SideSignUnButtonActionPerformed

    private void SideCreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SideCreateAccountButtonActionPerformed
      jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_SideCreateAccountButtonActionPerformed

    private void DATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATEActionPerformed

        updateSelectedDateLabel();
    }//GEN-LAST:event_DATEActionPerformed

    private void YEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YEARActionPerformed

        updateSelectedDateLabel();

    }//GEN-LAST:event_YEARActionPerformed

    private void MONTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MONTHActionPerformed

        updateSelectedDateLabel();
    }//GEN-LAST:event_MONTHActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateAccount;
    private javax.swing.JComboBox<String> DATE;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JComboBox<String> MONTH;
    private javax.swing.JButton SideCreateAccountButton;
    private javax.swing.JLabel SideLabel;
    private javax.swing.JButton SideSignUnButton;
    private javax.swing.JComboBox<String> YEAR;
    private javax.swing.JTextField ca_address;
    private javax.swing.JTextField ca_age;
    private javax.swing.JTextField ca_birthdate;
    private javax.swing.JButton ca_createbutton;
    private javax.swing.JTextField ca_email;
    public javax.swing.JTextField ca_fullname;
    private javax.swing.JComboBox<String> ca_gender;
    private javax.swing.JPasswordField ca_password;
    public javax.swing.JTextField ca_phonenumber;
    private javax.swing.JLabel ca_txtaddress;
    private javax.swing.JLabel ca_txtemail;
    private javax.swing.JLabel ca_txtemail1;
    private javax.swing.JLabel ca_txtemail2;
    private javax.swing.JLabel ca_txtemail4;
    private javax.swing.JLabel ca_txtfullname;
    private javax.swing.JLabel ca_txtgender;
    private javax.swing.JLabel ca_txtpassword;
    private javax.swing.JLabel ca_txtusername;
    private javax.swing.JTextField ca_username;
    private javax.swing.JPanel centerWhiteDesignPAnel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField login_password;
    private javax.swing.JTextField login_username;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JLabel logintxt_password;
    private javax.swing.JLabel logintxt_username1;
    private javax.swing.JCheckBox seePassword;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
